on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

permissions:
  id-token: write

jobs:
  madame_claude:
    uses: ./.github/workflows/run_spider.yml
    with:
      spider: madame_claude
