on:
  - workflow_dispatch

permissions:
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          pip install pipenv
      - run: |
          pipenv install
          pipenv run madame_claude
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::131164827647:role/GitHubActionsLimeChowRole
          aws-region: eu-central-1
      - run: |
          aws s3 sync out s3://lime-chow
