on:
  workflow_dispatch:
  schedule:
    - cron: '15 20 * * *'

permissions:
  id-token: write

jobs:
  peppi_guggenheim:
    uses: ./.github/workflows/run_spider.yml
    with:
      spider: peppi_guggenheim
